<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>dae98955-89f5-44e8-94fd-2254caec4b6a</testSuiteGuid>
   <testCaseLink>
      <guid>4c90ec87-2de3-4741-b1bd-b34b8a8ebb67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>44d684a3-bbe0-4de0-8d8d-b774d07d66ac</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>44d684a3-bbe0-4de0-8d8d-b774d07d66ac</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TabName</value>
         <variableId>ae6fda05-3c26-42f5-bc7f-b00db30e5d7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02af350a-e539-4178-8139-142163cea086</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
